language: go
go:
 - 1.8
install: make

after_success: sed -i "s/NEWRELICLICENSEKEY/$NEWRELIC_LICENSE_KEY/g" ./manifest.yml

deploy:
   edge: true
   provider: cloudfoundry
   username: $BM_USERNAME
   password: $BM_PASSWORD
   api: https://$BM_API
   organization: $BM_ORG
   space: dev

notifications:
  slack: tawerin:$SLACK_TOKEN
