language: go
go:
 - 1.8

before_install:
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
- echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
- sudo apt-get update
- sudo apt-get install cf-cli
- cf --version

env:
- SPACE=dev
- SPACE=prod

install: make

after_success:
  - ./deploy.sh

notifications:
  slack:
    rooms:
      - tawerin:6a1af05ead7bf3f03d582497975cfb7b446fafab
