language: go
go:
 - 1.8
install: make

env:
- DEV_SPACE=dev

before_deploy: sed -i "s/SPACE/$DEV_SPACE/g" ./manifest.yml

deploy:
   edge: true
   provider: cloudfoundry
   username: $BM_USERNAME
   password: $BM_PASSWORD
   api: https://$BM_API
   organization: $BM_ORG
   space: $DEV_SPACE

notifications:
  slack:
    rooms:
      - tawerin:6a1af05ead7bf3f03d582497975cfb7b446fafab
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
