language: go
go:
 - 1.8
install: make

after_success: sed -i "s/NEWRELICLICENSEKEY/$NEWRELIC_LICENSE_KEY/g" ./manifest.yml;sed -i "s/BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/g" ./manifest.yml

env:
- DEV_SPACE=dev
- PROD_SPACE=prod

before_deploy: sed -i "s/SPACE/$DEV_SPACE/g" ./manifest.yml

deploy:
   edge: true
   provider: cloudfoundry
   username: $BM_USERNAME
   password: $BM_PASSWORD
   api: https://$BM_API
   organization: $BM_ORG
   space: $SPACE

before_deploy: sed -i "s/SPACE/$PROD_SPACE/g" ./manifest.yml;sed -i "s/NEWRELICLICENSEKEY/$NEWRELIC_LICENSE_KEY/g" ./manifest.yml

deploy:
   edge: true
   provider: cloudfoundry
   username: $BM_USERNAME
   password: $BM_PASSWORD
   api: https://$BM_API
   organization: $BM_ORG
   space: $PROD_SPACE
   on:
    tags: true

notifications:
  slack:
    rooms:
      - tawerin:6a1af05ead7bf3f03d582497975cfb7b446fafab
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
